; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:board1]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.0
build_src_filter = +<board1_atmega2560.cpp> -<board2_atmega2560.cpp> -<esp32dev.cpp> -<board1_test.cpp> -<board2_test.cpp> -<esp32_test.cpp>

[env:board2]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.0
build_src_filter = +<board2_atmega2560.cpp> -<board1_atmega2560.cpp> -<esp32dev.cpp> -<board1_test.cpp> -<board2_test.cpp> -<esp32_test.cpp>

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = bblanchon/ArduinoJson @ ^7.4.3
build_src_filter = +<esp32dev.cpp> -<board1_atmega2560.cpp> -<board2_atmega2560.cpp> -<board1_test.cpp> -<board2_test.cpp> -<esp32_test.cpp>
monitor_dtr = 0
monitor_rts = 0

[env:esp32_test]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = bblanchon/ArduinoJson @ ^7.4.3
build_src_filter = +<esp32_test.cpp> -<board1_atmega2560.cpp> -<board2_atmega2560.cpp> -<board1_test.cpp> -<board2_test.cpp>
monitor_dtr = 0
monitor_rts = 0

[env:board1_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.0
build_src_filter = +<board1_test.cpp> -<board1_atmega2560.cpp> -<board2_atmega2560.cpp> -<esp32dev.cpp> -<board2_test.cpp> -<esp32_test.cpp>

[env:board2_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.0
build_src_filter = +<board2_test.cpp> -<board1_atmega2560.cpp> -<board2_atmega2560.cpp> -<esp32dev.cpp> -<esp32_test.cpp>
